### ISSUE TITLE
Long-term notes

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#14]
The deployment landscape is constantly evolving. There are a number of approaches to automating deployment, and it's not always easy to know what the stability of any one approach is. For example, Heroku has been moving away from classic buildpacks for a while now, but not very quickly. (See [here](https://github.com/heroku/heroku-buildpack-python/issues/796) for a long thread on adding Poetry support to Heroku.)

This is a collection of thoughts about possible directions to go. All of this is in line with the original intent of this project - hide the messiness and instability of deployment processes from developers of relatively simple Django projects as much as possible. When deployment processes change, update the internals of this package rather than changing developers' workflows.

**Comment by ehmatthes** [comment]
This should probably be restructured as an entry under docs/.

**Comment by ehmatthes** [comment]
- [ ] Consider using color for output.
    - See #70, but also see [syntax coloring](https://docs.djangoproject.com/en/4.0/ref/django-admin/#syntax-coloring) and [BaseCommand.style](https://docs.djangoproject.com/en/4.0/howto/custom-management-commands/#django.core.management.BaseCommand.style) in Django docs.
- [ ] Is there anything under [testing Management Commands](https://docs.djangoproject.com/en/4.0/topics/testing/tools/#topics-testing-management-commands) in the Django docs that I'm not currently using?

**Comment by ehmatthes** [comment]
Testing
---

- [ ] Test that an invalid command, ie omitting `--platform` flag, does not create a log dir.

**Comment by ehmatthes** [comment]
Documentation
---

- [ ] Mention option of confirming preliminary support status of a newly-supported platform in supporting_platforms.md. Link to a current or previous file with this confirmation, ie deploy_platformsh.py.

**Comment by ehmatthes** [comment]
Conventions
---

- [ ] Establish a clear line length convention.
    - [ ] Use Black?

**Comment by ehmatthes** [comment]
Manual (one-off) tests
---

- [ ] I have a Platform.sh account, so it's hard to test the workflow for automate_all when the user is logged in to the CLI, but has no organization.
    - [ ] Test this, perhaps by destroying my organization when I have no active projects.

**Comment by ehmatthes** [comment]
`--docs` flag
---

- [ ] Create a `--docs platform_name` flag, that will list the main entry points to that platform's docs as they relate to Django, and Python in general.

**Comment by ehmatthes** [comment]
Platform.sh deployments
---

- [ ] Is there any way to show progress during `project create`?
- [ ] Any way to show progress during `project push`?

**Comment by ehmatthes** [comment]
Developer support
---

- [ ] Consider more developer-focused flags.
    - [ ] For example, a `--no-deploy` flag might help when modifying the simple_deploy.py script. A block that exits just before `deploy()` is called, if this flag is set, would prevent any changes from being made to the test project. This saves some `git checkout .`, `git reset`, and `rm` calls.

**Comment by ehmatthes** [comment]
More misc
---

- [ ] Refactor `execute_subp_run()` into windows and posix methods, to reduce nesting.

**Comment by ehmatthes** [comment]
- [ ] Support wagtail deployments. See #173.

**Comment by ehmatthes** [comment]
Ensuring safe modifications
---

I've always been uncomfortable with the failure modes when simple_deploy can't finish its work after starting to make changes to the project. It's not a terrible situation, because people need to be using Git already, and we check for a clean status. But it still doesn't feel right to start making changes and then maybe have to bail on the user.

- [ ] Consider moving to a model where all changes are prepared in memory, and then only written to the user's project when we know that all necessary changes are ready. This is a more complicated approach, but should reduce significantly the number of projects that are left modified without being ready for deployment.
    - [ ] First thoughts at implementation: write all files to a temp dir, then copy to the user's project when we know there are no breaking issues.
    - [ ] Could start implementing this with logging.

**Comment by ehmatthes** [comment]
Logging
---

- [ ] Make sure all commands that are being run are logged. I believe some commands only have their output logged. See #260.
- [ ] Also from #260: Note for later that much of this logging could be moved to ie execute_command(), or execute_subp_run(). Would probably need skip_logging parameter.

**Comment by ehmatthes** [comment]
General
---

- [ ] Some of `_confirm_automate_all()` should be moved to either simple_deploy, or maybe even utils.
    - [ ] Or a parent class?
- [ ] Note: further refactoring could break `simple_deploy.Command` up into a class that handles package management issues. But the plugin model is higher priority. (Agreed, not now.)
