### ISSUE TITLE
Post-1.0 cleanup tasks

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#213]
These are important tasks, but they are not critical to a 1.0 release. They are great tasks for the 0.9 release through 1.0, if there are no new issues coming up from the 1.0 candidate.

- [ ] Adopt the policy that all open issues should be specific, and if addressed would be welcomed as a PR. Move all tasks in open issues that don't fit this description to a longer-term section of the docs.
- [ ] Implement an architecture that enforces structure of the `PlatformDeployer` classes. This is probably an ABC. Read a bit about composition and protols before making this decision, and [consider a plugin](https://github.com/ehmatthes/django-simple-deploy/discussions/266) approach as well.
- [ ] Use pytest to orchestrate integration tests.
- [ ] Clarify some of the use cases and more subtle benefits, ie "All configuration is contained in a single git commit". This makes it a great way to explore how a platform works.
- [ ] Rename `dsd_env` -> `.venv`.
- [ ] Use type hints where appropriate, particularly in the deployer classes.
- [ ] Move integration test docs to rtd.
