### ISSUE TITLE
Stabilize Fly.io deployments

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#263]
The initial implementation of support for Fly.io assumed you don't have any projects currently deployed to Fly. Revise the process so it works regardless of how many projects you currently have on Fly.io.

- [x] If more than one resource found, show the resources found (only most recently created ones, if many), and the one we think is correct. Ask for confirmation, or show a numbered list.
- [x] Test that this has not interfered with `--automate-all` workflow.
- [ ] Update integration tests to support deploying two projects.
- [x] Address any outstanding tasks or concerns in #101. Close that issue. (Not closing, but nothing left there that blocks closing this.)
- [x] Address any outstanding tasks or concerns in #259. Close that issue.
- [ ] Close any remaining issues labeled [fly.io](https://github.com/ehmatthes/django-simple-deploy/labels/fly.io).
- [x] Test on Windows.
    - [x] Unit tests.
    - [x] Integration tests. (Some issues with testing, see #272, but the actual deployment worked.)
- [ ] Update roadmap page.
- [x] Update documentation.
- [x] New release.
- [x] Test against PyPI.
- [ ] Announce, and request some testing.
    - [x] Mastodon
    - [ ] django forum
    - [ ] Make a quick terminal video showing process.

**Comment by ehmatthes** [comment]
Working notes
---

- [ ] Start a new branch.
- [ ] Set up a development project.
- [ ] Put a break in to show resources that are found.

**Comment by ehmatthes** [comment]
Notes
---

- Running `fly create` creates a new project on Fly, but does not make any local changes.

**Comment by ehmatthes** [comment]
Documentation notes
---

- [ ] In quick start guide, mention that migration is already done in deployment script.

**Comment by ehmatthes** [comment]
With multiple projects deployed
---

The output of `fly apps list` for one app that hasn't been deployed to yet is 136 lines. For one app that has just been deployed to, that jumps to 422! There should be something specific in there to help identify the most likely app to use.

There are three apps after deployment: the main app, the db app, and the fly-builder app. The builder app is sometimes present even if a successful deployment hasn't happened.

Tasks
---

- [ ] Can we identify whether an app is a db? (I'm not seeing any way to identify it. There's a `PostgresAppRole` field, but it's null for all of my listed apps, including the Postgres app. Processed all key-value pairs in app dict and pg dict, and there was no identifiable difference.

**Comment by ehmatthes** [comment]
Found a postgres db
---

When we find a postgres db with a name matching the app name, we can look at the users. Here's the output for a freshly created db that hasn't been attached to an app yet:

```
% fly postgres users list -a test-postgres-db
NAME      	SUPERUSER	DATABASES        
flypgadmin	yes      	postgres, repmgr	
postgres  	yes      	postgres, repmgr	
repmgr    	yes      	postgres, repmgr
```

Here's the output for a db that has been attached to an app (and had a successful migration):

```
% fly postgres users list -a black-voice-9060-db
NAME            	SUPERUSER	DATABASES                          
black_voice_9060	yes      	black_voice_9060, postgres, repmgr	
flypgadmin      	yes      	black_voice_9060, postgres, repmgr	
postgres        	yes      	black_voice_9060, postgres, repmgr	
repmgr          	yes      	black_voice_9060, postgres, repmgr
```

So, when we find a db:

- [ ] Make the `users list` call.
- [ ] Parse the output, and get a list of users.
- [ ] If we only find `flypgadmin`, `postgres`, and `repmgr`, it has likely not been attached. Display this info, and get confirmation to attach and proceed.
- [ ] If we find app-name in list of users, display this and get confirmation to proceed without attaching.

**Comment by ehmatthes** [comment]
Tests
---

- [ ] Run unit tests.
- [ ] Run integration tests.
- [ ] Consider a `--preexisting-app` flag? Consider two deployments?
    - [ ] Make sure to destroy all apps that are created.
- [ ] Test on Windows.
- [ ] Test on an Ubuntu VM.

**Comment by ehmatthes** [comment]
Notes testing work
---

- Integration tests will probably fail with a pre-existing app? Yes/no prompts are handled automatically during integration testing, but other interactive prompts are not. Probably need to store the app name, read the output, and select the correct name? Maybe always enter 1, if the apps are listed in order? What if the developer has multiple apps deployed on Fly???

**Comment by ehmatthes** [comment]
For remaining tasks, see #274.
